apiVersion: v1
kind: Service
metadata:
  name: hello-openshift
  namespace: migration-test
  labels:
    app: hello-ocp
spec:
  selector:
    app: hello-ocp
    deploymentconfig: hello-openshift
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: alt-http
      port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
