apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/ssl-redirect: "false"
  labels: app: hello-ocp
  name: hello-openshift
  namespace: migration-test
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - REPLACE_ME_HOST
      secretName: REPLACE_ME_TLS_SECRET
  rules:
    - host: REPLACE_ME_HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-openshift
                port:
                  number: 80